import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import { MusicProvider } from "@/contexts/MusicContext";
import AppShell from "@/components/layout/AppShell";
import Transaction from "@/components/layout/Transaction";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Rumani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MusicProvider>
          <Transaction />
          <AppShell>{children}</AppShell>
        </MusicProvider>
      </body>
    </html>
  );
}
